CREATE USER ece651_scraper WITH
    PASSWORD 'wxJcTdJYUU3mMAsAa5YD'
    LOGIN
    NOSUPERUSER
    NOINHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE USER ece651_ml WITH
    PASSWORD 'TVL3MV0mguz0DOhLbbm2'
    LOGIN
    NOSUPERUSER
    NOINHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE USER ece651_web WITH
    PASSWORD 'dm2fBdodbrHPtJVvlSKF'
    LOGIN
    NOSUPERUSER
    NOINHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

GRANT CONNECT ON DATABASE ece651 TO ece651_ml;
GRANT CONNECT ON DATABASE ece651 TO ece651_web;
GRANT CONNECT ON DATABASE ece651 TO ece651_scraper;


GRANT USAGE ON SCHEMA public TO ece651_ml;
GRANT USAGE ON SCHEMA public TO ece651_web;
GRANT USAGE ON SCHEMA public TO ece651_scraper;


GRANT SELECT ON ALL TABLES IN SCHEMA public TO ece651_ml;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO ece651_web;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO ece651_scraper;
