-- MySQL Script generated by MySQL Workbench
-- Fri Feb  8 14:24:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema ece651
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ece651
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "ece651"  ;

-- -----------------------------------------------------
-- Table "ece651"."Books"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Books" (
  "book_id" INT NOT NULL ,
  "title" VARCHAR(200) NOT NULL,
  "series" VARCHAR(200) NULL,
  "series_position" INT NULL,
  "pages" INT NULL,
  "publisher" VARCHAR(200) NULL,
  "orig_published_date" DATE NULL,
  "ISBN10" VARCHAR(10) NULL,
  "ISBN13" VARCHAR(15) NULL,
  "synopsis" TEXT NULL,
  PRIMARY KEY ("book_id"));


-- -----------------------------------------------------
-- Table "ece651"."Users"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Users" (
  "user_id" INT NOT NULL ,
  "display_name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(200) NOT NULL,
  "password_hash" VARCHAR(65) NOT NULL,
  "password_salt" VARCHAR(50) NOT NULL,
  "creation_time" TIMESTAMP NOT NULL DEFAULT now(),
  "preferences_json" TEXT NOT NULL DEFAULT '{}',
  "created_from" TEXT NOT NULL,
  "login_allowed" TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("user_id"),


-- -----------------------------------------------------
-- Table "ece651"."Categories"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Categories" (
  "categories_id" INT NOT NULL ,
  "name" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("categories_id"));


-- -----------------------------------------------------
-- Table "ece651"."Reviews"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Reviews" (
  "review_id" INT NOT NULL ,
  "user_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  "rating" INT NOT NULL,
  "review" TEXT NULL,
  PRIMARY KEY ("review_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "ece651"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "ece651"."Users" ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "ece651"."Book_Category"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Book_Category" (
  "book_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY ("book_id", "category_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "ece651"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "category_id_fk"
    FOREIGN KEY ("category_id")
    REFERENCES "ece651"."Categories" ("categories_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "ece651"."AmazonDetails"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."AmazonDetails" (
  "book_id" INT NOT NULL,
  "book_link" TEXT NOT NULL,
  "rating" DECIMAL NULL,
  "synopsis" TEXT NULL,
  "price" DECIMAL NULL,
  PRIMARY KEY ("book_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "ece651"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "ece651"."Author"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."Author" (
  "author_id" INT NOT NULL ,
  "last_name" VARCHAR(100) NOT NULL,
  "first_name" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("author_id"));


-- -----------------------------------------------------
-- Table "ece651"."AuthorBooks"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."AuthorBooks" (
  "author_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  PRIMARY KEY ("author_id", "book_id"),
  CONSTRAINT "author_id_fk"
    FOREIGN KEY ("author_id")
    REFERENCES "ece651"."Author" ("author_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "ece651"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "ece651"."BookOfTheDay"
-- -----------------------------------------------------
CREATE TABLE  "ece651"."BookOfTheDay" (
  "idBookOfTheDay" INT NOT NULL ,
  "book_id" INT NOT NULL,
  "date" DATE NOT NULL,
  PRIMARY KEY ("idBookOfTheDay"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "ece651"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP SEQUENCE IF EXISTS "ece651"."Books_book_id_sequence";
CREATE SEQUENCE  "ece651"."Books_book_id_sequence";
ALTER TABLE "ece651"."Books" ALTER COLUMN "book_id" SET DEFAULT NEXTVAL('"ece651"."Books_book_id_sequence"');
DROP SEQUENCE IF EXISTS "ece651"."Users_user_id_sequence";
CREATE SEQUENCE  "ece651"."Users_user_id_sequence";
ALTER TABLE "ece651"."Users" ALTER COLUMN "user_id" SET DEFAULT NEXTVAL('"ece651"."Users_user_id_sequence"');
DROP SEQUENCE IF EXISTS "ece651"."Categories_categories_id_sequence";
CREATE SEQUENCE  "ece651"."Categories_categories_id_sequence";
ALTER TABLE "ece651"."Categories" ALTER COLUMN "categories_id" SET DEFAULT NEXTVAL('"ece651"."Categories_categories_id_sequence"');
DROP SEQUENCE IF EXISTS "ece651"."Reviews_review_id_sequence";
CREATE SEQUENCE  "ece651"."Reviews_review_id_sequence";
ALTER TABLE "ece651"."Reviews" ALTER COLUMN "review_id" SET DEFAULT NEXTVAL('"ece651"."Reviews_review_id_sequence"');
DROP SEQUENCE IF EXISTS "ece651"."Author_author_id_sequence";
CREATE SEQUENCE  "ece651"."Author_author_id_sequence";
ALTER TABLE "ece651"."Author" ALTER COLUMN "author_id" SET DEFAULT NEXTVAL('"ece651"."Author_author_id_sequence"');
DROP SEQUENCE IF EXISTS "ece651"."BookOfTheDay_idBookOfTheDay_sequence";
CREATE SEQUENCE  "ece651"."BookOfTheDay_idBookOfTheDay_sequence";
ALTER TABLE "ece651"."BookOfTheDay" ALTER COLUMN "idBookOfTheDay" SET DEFAULT NEXTVAL('"ece651"."BookOfTheDay_idBookOfTheDay_sequence"');
