-- MySQL Script generated by MySQL Workbench
-- Wed Feb  6 15:43:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table "public"."Books"
-- -----------------------------------------------------
CREATE TABLE  "public"."Books" (
  "book_id" INT NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "series" VARCHAR(200) NULL,
  "series_position" INT NULL,
  "pages" INT NULL,
  "publisher" VARCHAR(200) NULL,
  "orig_published_date" DATE NULL,
  "ISBN10" VARCHAR(10) NULL,
  "ISBN13" VARCHAR(15) NULL,
  "synopsis" TEXT NULL,
  PRIMARY KEY ("book_id"));


-- -----------------------------------------------------
-- Table "public"."Users"
-- -----------------------------------------------------
CREATE TABLE  "public"."Users" (
  "user_id" INT NOT NULL,
  "login_name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(200) NOT NULL,
  "password_hash" VARCHAR(65) NOT NULL,
  "password_salt" VARCHAR(50) NOT NULL,
  PRIMARY KEY ("user_id"));


-- -----------------------------------------------------
-- Table "public"."Categories"
-- -----------------------------------------------------
CREATE TABLE  "public"."Categories" (
  "categories_id" INT NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("categories_id"));


-- -----------------------------------------------------
-- Table "public"."Reviews"
-- -----------------------------------------------------
CREATE TABLE  "public"."Reviews" (
  "review_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  "rating" INT NOT NULL,
  "review" TEXT NULL,
  PRIMARY KEY ("review_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "public"."Users" ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "public"."Book_Category"
-- -----------------------------------------------------
CREATE TABLE  "public"."Book_Category" (
  "book_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY ("book_id", "category_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "category_id_fk"
    FOREIGN KEY ("category_id")
    REFERENCES "public"."Categories" ("categories_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "public"."AmazonDetails"
-- -----------------------------------------------------
CREATE TABLE  "public"."AmazonDetails" (
  "book_id" INT NOT NULL,
  "book_link" TEXT NOT NULL,
  "rating" DECIMAL NULL,
  "synopsis" TEXT NULL,
  "price" DECIMAL NULL,
  PRIMARY KEY ("book_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "public"."Author"
-- -----------------------------------------------------
CREATE TABLE  "public"."Author" (
  "author_id" INT NOT NULL,
  "last_name" VARCHAR(100) NOT NULL,
  "first_name" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("author_id"));


-- -----------------------------------------------------
-- Table "public"."AuthorBooks"
-- -----------------------------------------------------
CREATE TABLE  "public"."AuthorBooks" (
  "author_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  PRIMARY KEY ("author_id", "book_id"),
  CONSTRAINT "author_id_fk"
    FOREIGN KEY ("author_id")
    REFERENCES "public"."Author" ("author_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


