-- MySQL Script generated by MySQL Workbench
-- Fri Feb  8 14:49:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema ece651
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ece651
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "public"  ;

-- -----------------------------------------------------
-- Table "public"."Books"
-- -----------------------------------------------------
CREATE TABLE  "public"."Books" (
  "book_id" INT NOT NULL ,
  "title" VARCHAR(200) NOT NULL,
  "series" VARCHAR(200) NULL,
  "series_position" INT NULL,
  "pages" INT NULL,
  "publisher" VARCHAR(200) NULL,
  "orig_published_date" DATE NULL,
  "isbn10" VARCHAR(10) NULL,
  "isbn13" VARCHAR(15) NULL,
  "synopsis" TEXT NULL,
  PRIMARY KEY ("book_id"));


-- -----------------------------------------------------
-- Table "public"."Users"
-- -----------------------------------------------------
CREATE TABLE  "public"."Users" (
  "user_id" INT NOT NULL ,
  "display_name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(200) NOT NULL,
  "password_hash" VARCHAR(65) NOT NULL,
  "password_salt" VARCHAR(50) NOT NULL,
  "creation_time" TIMESTAMP NOT NULL DEFAULT now(),
  "preferences_json" TEXT NOT NULL DEFAULT '{}',
  "created_from" TEXT NOT NULL,
  "login_allowed" INT NOT NULL DEFAULT 0,
  PRIMARY KEY ("user_id"));



-- -----------------------------------------------------
-- Table "public"."Categories"
-- -----------------------------------------------------
CREATE TABLE  "public"."Categories" (
  "categories_id" INT NOT NULL ,
  "name" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("categories_id"));


-- -----------------------------------------------------
-- Table "public"."Reviews"
-- -----------------------------------------------------
CREATE TABLE  "public"."Reviews" (
  "review_id" INT NOT NULL ,
  "user_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  "rating" INT NOT NULL,
  "review" TEXT NULL,
  PRIMARY KEY ("review_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "public"."Users" ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);




-- -----------------------------------------------------
-- Table "public"."BookCategory"
-- -----------------------------------------------------
CREATE TABLE  "public"."BookCategories" (
  "book_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY ("book_id", "category_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "category_id_fk"
    FOREIGN KEY ("category_id")
    REFERENCES "public"."Categories" ("categories_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table "public"."AmazonDetails"
-- -----------------------------------------------------
CREATE TABLE  "public"."AmazonDetails" (
  "book_id" INT NOT NULL,
  "book_link" TEXT NOT NULL,
  "rating" DECIMAL NULL,
  "num_reviews" INT NULL,
  "synopsis" TEXT NULL,
  "price" DECIMAL NULL,
  PRIMARY KEY ("book_id"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "public"."Author"
-- -----------------------------------------------------
CREATE TABLE  "public"."Author" (
  "author_id" INT NOT NULL ,
  "name" VARCHAR(200) NOT NULL,
  PRIMARY KEY ("author_id"));


-- -----------------------------------------------------
-- Table "public"."AuthorBooks"
-- -----------------------------------------------------
CREATE TABLE  "public"."AuthorBooks" (
  "author_id" INT NOT NULL,
  "book_id" INT NOT NULL,
  PRIMARY KEY ("author_id", "book_id"),
  CONSTRAINT "author_id_fk"
    FOREIGN KEY ("author_id")
    REFERENCES "public"."Author" ("author_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table "public"."BookOfTheDay"
-- -----------------------------------------------------
CREATE TABLE  "public"."BookOfTheDay" (
  "idBookOfTheDay" INT NOT NULL ,
  "book_id" INT NOT NULL,
  "date" DATE NOT NULL,
  PRIMARY KEY ("idBookOfTheDay"),
  CONSTRAINT "book_id_fk"
    FOREIGN KEY ("book_id")
    REFERENCES "public"."Books" ("book_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



DROP SEQUENCE IF EXISTS "public"."Books_book_id_sequence";
CREATE SEQUENCE  "public"."Books_book_id_sequence";
ALTER TABLE "public"."Books" ALTER COLUMN "book_id" SET DEFAULT NEXTVAL('"public"."Books_book_id_sequence"');
DROP SEQUENCE IF EXISTS "public"."Users_user_id_sequence";
CREATE SEQUENCE  "public"."Users_user_id_sequence";
ALTER TABLE "public"."Users" ALTER COLUMN "user_id" SET DEFAULT NEXTVAL('"public"."Users_user_id_sequence"');
DROP SEQUENCE IF EXISTS "public"."Categories_categories_id_sequence";
CREATE SEQUENCE  "public"."Categories_categories_id_sequence";
ALTER TABLE "public"."Categories" ALTER COLUMN "categories_id" SET DEFAULT NEXTVAL('"public"."Categories_categories_id_sequence"');
DROP SEQUENCE IF EXISTS "public"."Reviews_review_id_sequence";
CREATE SEQUENCE  "public"."Reviews_review_id_sequence";
ALTER TABLE "public"."Reviews" ALTER COLUMN "review_id" SET DEFAULT NEXTVAL('"public"."Reviews_review_id_sequence"');
DROP SEQUENCE IF EXISTS "public"."Author_author_id_sequence";
CREATE SEQUENCE  "public"."Author_author_id_sequence";
ALTER TABLE "public"."Author" ALTER COLUMN "author_id" SET DEFAULT NEXTVAL('"public"."Author_author_id_sequence"');
DROP SEQUENCE IF EXISTS "public"."BookOfTheDay_idBookOfTheDay_sequence";
CREATE SEQUENCE  "public"."BookOfTheDay_idBookOfTheDay_sequence";
ALTER TABLE "public"."BookOfTheDay" ALTER COLUMN "idBookOfTheDay" SET DEFAULT NEXTVAL('"public"."BookOfTheDay_idBookOfTheDay_sequence"');


ALTER TABLE public."Books" ADD CONSTRAINT unique_isbn10 UNIQUE ("isbn10");
ALTER TABLE public."Books" ADD CONSTRAINT unique_isbn13 UNIQUE ("isbn13");
ALTER TABLE public."Users" ADD CONSTRAINT unique_email UNIQUE (email);
ALTER TABLE public."Categories" ADD CONSTRAINT unique_cat_name UNIQUE ("name");
ALTER TABLE public."Author" ADD CONSTRAINT unique_author_name UNIQUE ("name");


CREATE OR REPLACE VIEW public."BookDetails" AS
 SELECT "Books".book_id,
    "Books".title,
	abb.author_id,
	abb.author_name,
    "Books".series,
    "Books".series_position,
    "Books".pages,
    "Books".publisher,
    "Books".orig_published_date,
    "Books".isbn10,
    "Books".isbn13,
    "Books".synopsis,
    ad.book_link AS amazon_link,
    ad.rating AS amazon_rating,
    ad.synopsis AS amazon_synopsis,
    ad.price AS amazon_price,
    ad.num_reviews AS amazon_num_reviews
   FROM "Books"
     INNER JOIN "AmazonDetails" ad ON "Books".book_id = ad.book_id
	 Left JOIN (SELECT distinct on (ab.book_id) a.author_id, ab.book_id, a."name" as author_name from "Author" as a
inner join "AuthorBooks" ab on a.author_id = ab.author_id) abb ON "Books".book_id = abb.book_id;


GRANT USAGE ON SCHEMA public TO ece651_scraper;
GRANT USAGE ON SCHEMA public TO ece651_ml;
GRANT USAGE ON SCHEMA public TO ece651_web;

GRANT ALL ON TABLE public."AmazonDetails" TO ece651_ml;
GRANT ALL ON TABLE public."AmazonDetails" TO ece651_web;
GRANT ALL ON TABLE public."AmazonDetails" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."Author_author_id_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."Author_author_id_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."Author_author_id_sequence" TO ece651_web;

GRANT ALL ON TABLE public."Author" TO ece651_ml;
GRANT ALL ON TABLE public."Author" TO ece651_web;
GRANT ALL ON TABLE public."Author" TO ece651_scraper;

GRANT ALL ON TABLE public."AuthorBooks" TO ece651_ml;
GRANT ALL ON TABLE public."AuthorBooks" TO ece651_web;
GRANT ALL ON TABLE public."AuthorBooks" TO ece651_scraper;

GRANT ALL ON TABLE public."BookCategories" TO ece651_ml;
GRANT ALL ON TABLE public."BookCategories" TO ece651_web;
GRANT ALL ON TABLE public."BookCategories" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."BookOfTheDay_idBookOfTheDay_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."BookOfTheDay_idBookOfTheDay_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."BookOfTheDay_idBookOfTheDay_sequence" TO ece651_web;

GRANT ALL ON TABLE public."BookOfTheDay" TO ece651_ml;
GRANT ALL ON TABLE public."BookOfTheDay" TO ece651_web;
GRANT ALL ON TABLE public."BookOfTheDay" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."Books_book_id_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."Books_book_id_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."Books_book_id_sequence" TO ece651_web;

GRANT ALL ON TABLE public."Books" TO ece651_ml;
GRANT ALL ON TABLE public."Books" TO ece651_web;
GRANT ALL ON TABLE public."Books" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."Categories_categories_id_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."Categories_categories_id_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."Categories_categories_id_sequence" TO ece651_web;

GRANT ALL ON TABLE public."Categories" TO ece651_ml;
GRANT ALL ON TABLE public."Categories" TO ece651_web;
GRANT ALL ON TABLE public."Categories" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."Reviews_review_id_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."Reviews_review_id_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."Reviews_review_id_sequence" TO ece651_web;

GRANT ALL ON TABLE public."Reviews" TO ece651_ml;
GRANT ALL ON TABLE public."Reviews" TO ece651_web;
GRANT ALL ON TABLE public."Reviews" TO ece651_scraper;

GRANT ALL ON SEQUENCE public."Users_user_id_sequence" TO ece651_scraper;
GRANT ALL ON SEQUENCE public."Users_user_id_sequence" TO ece651_ml;
GRANT ALL ON SEQUENCE public."Users_user_id_sequence" TO ece651_web;

GRANT ALL ON TABLE public."Users" TO ece651_ml;
GRANT ALL ON TABLE public."Users" TO ece651_web;
GRANT ALL ON TABLE public."Users" TO ece651_scraper;

GRANT ALL ON TABLE public."BookDetails" TO ece651_ml;
GRANT ALL ON TABLE public."BookDetails" TO ece651_web;
GRANT ALL ON TABLE public."BookDetails" TO ece651_scraper;
